language: objective-c
osx_image: xcode7.2
before_install:
  - brew install xctool

script:   
  - >
    xcodebuild -project "Proj4.xcodeproj" \
      -destination "OS=9.2,name=iPhone 6s" \
      -sdk "iphonesimulator9.2" \
      -scheme "Proj4" \
      -configuration Debug \
      test | xcpretty -c;
