language: objective-c
osx_image: xcode7.2
before_install:
  - brew install xctool

script:   
  - >
    xcodebuild -project "Proj4Swift.xcodeproj" \
      -destination "OS=9.3,name=iPhone 6s" \
      -sdk "iphonesimulator9.3" \
      -scheme "Proj4Swift" \
      -configuration Debug \
      test | xcpretty -c;
